name: personalized_travel_recommendations
description: A new Flutter project.

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9

  cupertino_icons: ^1.0.2

flutter:
  assets:
    - lib/assets/icons/

dev_dependencies:
  flutter_lints: ^2.0.1
