name: personalized_travel_recommendations
description: A new Flutter project.

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.8
  table_calendar: ^3.2.0
  intl: ^0.20.2
  google_maps_flutter: ^2.12.2
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.1

flutter:
  assets:
    - assets/logos/
    - assets/icons/Outline/png/
    - assets/icons/Outline/svg 1x/
    - assets/icons/Solid/png/
    - assets/icons/Solid/svg 1x/
    - assets/images/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.otf
        - asset: assets/fonts/Pretendard-Bold.otf
        - asset: assets/fonts/Pretendard-Light.otf
        - asset: assets/fonts/Pretendard-Medium.otf
        - asset: assets/fonts/Pretendard-SemiBold.otf
        - asset: assets/fonts/Pretendard-ExtraBold.otf

dev_dependencies:
  flutter_lints: ^3.0.1
